#!/bin/bash
# Quick Commands to Connect Frontend & Backend to Database

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║              CRM QUICK START - ALL COMMANDS                    ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# For Windows PowerShell users, prefix with 'cd' commands shown below

echo "═══════════════════════════════════════════════════════════════════"
echo "TERMINAL 1: BACKEND"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# Copy and paste these commands:"
echo ""
echo "cd backend"
echo "python -m venv venv"
echo ""
echo "# For Windows:"
echo ".\venv\Scripts\Activate.ps1"
echo ""
echo "# For Mac/Linux:"
echo "source venv/bin/activate"
echo ""
echo "pip install -r requirements.txt"
echo "python -m alembic upgrade head"
echo "uvicorn app.main:app --reload --port 8085"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "TERMINAL 2: FRONTEND"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# Copy and paste these commands:"
echo ""
echo "cd frontend"
echo "python simple_server.py"
echo ""
echo "# Opens on http://localhost:3000"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "TERMINAL 3: TESTING (after both are running)"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# To test database connection:"
echo ""
echo "cd backend"
echo "python test_integration.py"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "DATABASE MIGRATION COMMANDS"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# View current migration status:"
echo "python -m alembic current"
echo ""
echo "# View all migrations:"
echo "python -m alembic history"
echo ""
echo "# Apply migrations:"
echo "python -m alembic upgrade head"
echo ""
echo "# Rollback one migration:"
echo "python -m alembic downgrade -1"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "TESTING COMMANDS"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# Test components (run in backend directory):"
echo "python test_target_endpoints.py"
echo "python test_workflow_simulation.py"
echo "python test_frontend_integration.py"
echo "python test_integration.py"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "BROWSER CONSOLE TESTS"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# Open browser at http://localhost:3000"
echo "# Open Developer Tools (F12)"
echo "# Go to Console tab"
echo "# Paste this code:"
echo ""
echo "fetch('http://localhost:8085/health')"
echo "  .then(r => r.json())"
echo "  .then(data => console.log('✓ Backend connected:', data))"
echo "  .catch(err => console.error('✗ Backend not connected:', err));"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "CHECKING SERVICES"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# Check if port 8085 is in use:"
echo "netstat -ano | findstr :8085"
echo ""
echo "# Check if port 3000 is in use:"
echo "netstat -ano | findstr :3000"
echo ""
echo "# Check if PostgreSQL can be reached:"
echo "ping 187.127.149.245"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "API ENDPOINTS TO TEST"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# In browser:"
echo ""
echo "http://localhost:8085/docs              # Swagger API documentation"
echo "http://localhost:8085/redoc             # ReDoc documentation"
echo "http://localhost:8085/health            # Health check"
echo "http://localhost:3000                   # Frontend"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "COMMON ISSUES"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Issue: 'uvicorn command not found'"
echo "Fix: Run 'pip install -r requirements.txt' first"
echo ""
echo "Issue: 'Port 8085 already in use'"
echo "Fix: Kill process or use different port: --port 8086"
echo ""
echo "Issue: 'Database connection refused'"
echo "Fix: Check .env DATABASE_URL is correct"
echo "    Or use local PostgreSQL instead"
echo ""
echo "Issue: 'Frontend can't connect to backend'"
echo "Fix: Check CORS settings in .env"
echo "    Or manually set: localStorage.setItem('crm_api_base', 'http://localhost:8085')"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "✓ Everything is set up!"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
