"""add lead followup and deal value

Revision ID: add_lead_followup_and_deal_value
Revises: merge_all_heads
Create Date: 2025-01-15 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_lead_followup_and_deal_value'
down_revision = 'merge_all_heads'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('followup_date', sa.Date(), nullable=True))
    op.add_column('leads', sa.Column('deal_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'deal_value')
    op.drop_column('leads', 'followup_date')
    # ### end Alembic commands ###
